services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped

    command:
      - redis-server

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 3s
      retries: 10


  db:
    image: postgis/postgis:14-3.4-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: umap
      POSTGRES_USER: umap
      POSTGRES_PASSWORD: ${UMAP_DB_PASSWORD}

    volumes:
      - db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umap -d umap"]
      interval: 2s
      timeout: 5s
      retries: 20


  app:
    image: umap/umap:3.7.3
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

      redis:
        condition: service_healthy

    environment:
      DATABASE_URL: postgis://umap:${UMAP_DB_PASSWORD}@db:5432/umap

      SECRET_KEY: ${UMAP_SECRET_KEY}

      SITE_URL: ${UMAP_SITE_URL}

      CSRF_TRUSTED_ORIGINS: ${UMAP_CSRF_TRUSTED_ORIGINS}

      ENABLE_ACCOUNT_LOGIN: "1"
      UMAP_ALLOW_ANONYMOUS: "0"

      STATIC_ROOT: /srv/umap/static
      MEDIA_ROOT: /srv/umap/uploads

      REALTIME_ENABLED: "1"
      REDIS_URL: redis://redis:6379

      DEBUG: "0"

    volumes:
      - data:/srv/umap/uploads
      - static:/srv/umap/static

      # Internal HTTP configuration
      - ./docker/umap-internal.conf:/etc/umap/umap.conf:ro


  proxy:
    image: nginx:1.29-alpine
    restart: unless-stopped

    depends_on:
      - app

    ports:
      - "8015:80"

    volumes:
      - ./docker/umap-snippet.conf:/etc/nginx/snippets/umap.conf:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro

      - static:/static:ro
      - data:/data:ro


volumes:
  data:
  static:
  db:
